version: "2"
services:
  app:
    build: ./app
    links:
      - mysqldb
    ports:
      - "8000:8000"
    environment:
      - DB_URL=mysql+pymysql://root:${MYSQL_ROOT_PASSWORD}@mysqldb:3306/${MYSQL_DATABASE}
    depends_on:
      mysqldb:
        condition: service_healthy
  mysqldb:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password  
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - ./db_scripts/mysql-init-files:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "--password=$$MYSQL_ROOT_PASSWORD"]
      timeout: 20s
      retries: 10

volumes:
  db: {}