version: "2"
services:
  app:
    build: ./app
    links:
      - mysqldb
    ports:
      - "8000:80"
    environment:
      - DB_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_USER}@mysqldb:3306/${MYSQL_DATABASE}
    depends_on:
      mysqldb:
        condition: service_healthy
  mysqldb:
    platform: linux/amd64
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - db_data://var/lib/mysql
      - ./mysql-init-files:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-p"]
      timeout: 20s
      retries: 10

  volumes:
    db_data: {}